title: YEAR 100 MILLION B.C.
description: FERAL PREHISTORIC RPG

theme: just-the-docs

logo: "/year100millionbc/assets/img/LogoThreeDudes.png"

url: "https://goldenachiever.github.io"
baseurl: "/year100millionbc"

just_the_docs:
  custom_css:
    - assets/css/custom.css
