title: YEAR 100 MILLION B.C.
logo: "/assets/img/LogoThreeDudes.png"
logo_width: 200
description: FERAL PREHISTORIC RPG
theme: just-the-docs

url: http://github.com/GoldenAchiever/year100millionbc

aux_links_new_tab: true

sass:
  load_paths:
    - _sass

# Enable custom CSS
include:
  - assets/css
