title: YEAR 100 MILLION B.C.
description: FERAL PREHISTORIC RPG

theme: just-the-docs

logo: "/assets/img/WideLogo.png"

url: "https://goldenachiever.github.io"
baseurl: "/year100millionbc"

aux_links_new_tab: true

just_the_docs:
  color_scheme: custom
